mod_sql_mysql: tweak build for mysql-8 ('my_bool' removal)
https://bugs.mysql.com/bug.php?id=85131 removed 'my_bool'
in favour of 'bool' from <stdbool.h> or c++'s 'bool'.

That causes build failure like:

```
mod_sql_mysql.c: In function ‘cmd_open’:
mod_sql_mysql.c:498:5: error: unknown type name ‘my_bool’; did you mean ‘bool’?
  498 |     my_bool reconnect = TRUE;
      |     ^~~~~~~
      |     bool
```

The change adds conditional use of 'bool'/'my_bool' based on 'MYSQL_VERSION_ID'.

Reported-by: Toralf Förster
Bug: https://bugs.gentoo.org/692434
Closes: https://github.com/proftpd/proftpd/issues/824
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>