Fix minor packet ordering when sending the `EXT_INFO` message during KEX.
Per RFC 8308, the `EXT_INFO` message should be sent after `NEWKEYS`.  But
the traffic policy support _might_ send an `IGNORE` message, after `NEWKEYS`
but before `EXT_INFO`, when CBC ciphers are used.  And at least one client
(PuTTy) properly complained when this unexpected packet ordering occurred:
```
Initialised Blowfish-128 CBC outbound encryption
Initialised HMAC-SHA-256 (unaccelerated) outbound MAC algorithm
Initialised Blowfish-128 CBC inbound encryption
Initialised HMAC-SHA-256 (unaccelerated) inbound MAC algorithm
Remote side sent SSH2_MSG_EXT_INFO not either preceded by NEWKEYS or followed by USERAUTH_SUCCESS
FATAL ERROR: Remote side sent SSH2_MSG_EXT_INFO not either preceded by NEWKEYS or followed by USERAUTH_SUCCESS
```